#
# !!! DO NOT EDIT THIS FILE, IT IS GENERATED !!!
#
# For more information, see tools/generate_class.py.
#
import re
import pydantic
from pydantic import constr
from typing import List, Dict, Optional


# Some ASFF classes have inconsistent naming, e.g. 'SseType' or 'SSEAlgorithm'.
# This dict collects such exception.
_ALIAS_NORMALIZER = {
    "sse_algorithm": "SSEAlgorithm",
    "kms_master_key_id": "KMSMasterKeyID",
}


class ASFFBaseModel(pydantic.BaseModel):
    class Config:
        validate_assignment = True
        allow_population_by_field_name = True
        alias_generator = lambda x: _ALIAS_NORMALIZER.get(
            x, re.sub(r"(?:^|_)(.)", lambda m: m.group(1).upper(), x)
        )
